import { Data } from './Data';
import { DataSources, Types } from '../types';
import { countPropertiesInObject, genID, isValid } from '@/shared/scripts/constants';

export class Shop extends Data {
  [key: string]: any;

  shopifyID?: number | string;
  domain?: string = ``;
  myshopifyDomain?: string = ``;
  customerEmail?: string = ``;
  shopOwner?: string = ``;
  phone?: string = ``;
  address1?: string = ``;
  address2?: string = ``;
  city?: string = ``;
  province?: string = ``;
  provinceCode?: string = ``;
  zip?: string = ``;
  country?: string = ``;
  countryCode?: string = ``;
  countryName?: string = ``;
  latitude?: number = 0;
  longitude?: number = 0;
  currency?: string = `usd`;
  moneyFormat?: string = ``;
  moneyWithCurrencyFormat?: string = ``;
  moneyInEmailsFormat?: string = ``;
  moneyWithCurrencyInEmailsFormat?: string = ``;
  primaryLocale?: string = `en`;
  timezone?: string = ``;
  ianaTimezone?: string = ``;
  weightUnit?: string = `lb`;
  taxesIncluded?: boolean = false;
  taxShipping?: boolean | null = null;
  countyTaxes?: boolean = false;
  autoConfigureTaxInclusivity?: boolean | null = null;
  planName?: string = ``;
  planDisplayName?: string = ``;
  hasDiscounts?: boolean = false;
  hasGiftCards?: boolean = false;
  eligibleForPayments?: boolean = false;
  requiresExtraPaymentsAgreement?: boolean = false;
  passwordEnabled?: boolean = false;
  hasStorefront?: boolean = true;
  finances?: boolean = false;
  primaryLocationID?: number = 0;
  checkoutAPISupported?: boolean = false;
  multiLocationEnabled?: boolean = false;
  setupRequired?: boolean = false;
  preLaunchEnabled?: boolean = false;
  enabledPresentmentCurrencies?: string[] = [];
  createdAt?: string = ``;
  updatedAt?: string = ``;
  source?: string = ``;
  type: Types = Types.Shop;
  dataSource?: DataSources | string = DataSources.firebase;

  constructor(data: Partial<Shop> = {}) {
    const shopData = data as Partial<Shop> & Record<string, any>;
    const shopName = shopData.name || shopData.domain || shopData.myshopify_domain || shopData.myshopifyDomain || `Shop`;
    super({ ...shopData, name: shopName, type: Types.Shop, created: shopData.created ?? shopData.created_at, updated: shopData.updated ?? shopData.updated_at });
    Object.assign(this, shopData);

    if (isValid(shopData.id) && !isValid(this.shopifyID) && typeof shopData.id == `number`) this.shopifyID = shopData.id;
    if (!isValid(this.name)) this.name = shopName;
    if (isValid(shopData.myshopify_domain) && !isValid(this.myshopifyDomain)) this.myshopifyDomain = shopData.myshopify_domain;
    if (isValid(shopData.customer_email) && !isValid(this.customerEmail)) this.customerEmail = shopData.customer_email;
    if (isValid(shopData.shop_owner) && !isValid(this.shopOwner)) this.shopOwner = shopData.shop_owner;
    if (isValid(shopData.country_code) && !isValid(this.countryCode)) this.countryCode = shopData.country_code;
    if (isValid(shopData.country_name) && !isValid(this.countryName)) this.countryName = shopData.country_name;
    if (isValid(shopData.province_code) && !isValid(this.provinceCode)) this.provinceCode = shopData.province_code;
    if (isValid(shopData.primary_locale) && !isValid(this.primaryLocale)) this.primaryLocale = shopData.primary_locale;
    if (isValid(shopData.iana_timezone) && !isValid(this.ianaTimezone)) this.ianaTimezone = shopData.iana_timezone;
    if (isValid(shopData.weight_unit) && !isValid(this.weightUnit)) this.weightUnit = shopData.weight_unit;
    if (isValid(shopData.money_format) && !isValid(this.moneyFormat)) this.moneyFormat = shopData.money_format;
    if (isValid(shopData.money_with_currency_format) && !isValid(this.moneyWithCurrencyFormat)) this.moneyWithCurrencyFormat = shopData.money_with_currency_format;
    if (isValid(shopData.money_in_emails_format) && !isValid(this.moneyInEmailsFormat)) this.moneyInEmailsFormat = shopData.money_in_emails_format;
    if (isValid(shopData.money_with_currency_in_emails_format) && !isValid(this.moneyWithCurrencyInEmailsFormat)) this.moneyWithCurrencyInEmailsFormat = shopData.money_with_currency_in_emails_format;
    if (shopData.taxes_included !== undefined) this.taxesIncluded = shopData.taxes_included;
    if (shopData.tax_shipping !== undefined) this.taxShipping = shopData.tax_shipping;
    if (shopData.county_taxes !== undefined) this.countyTaxes = shopData.county_taxes;
    if (shopData.auto_configure_tax_inclusivity !== undefined) this.autoConfigureTaxInclusivity = shopData.auto_configure_tax_inclusivity;
    if (isValid(shopData.plan_name) && !isValid(this.planName)) this.planName = shopData.plan_name;
    if (isValid(shopData.plan_display_name) && !isValid(this.planDisplayName)) this.planDisplayName = shopData.plan_display_name;
    if (shopData.has_discounts !== undefined) this.hasDiscounts = shopData.has_discounts;
    if (shopData.has_gift_cards !== undefined) this.hasGiftCards = shopData.has_gift_cards;
    if (shopData.eligible_for_payments !== undefined) this.eligibleForPayments = shopData.eligible_for_payments;
    if (shopData.requires_extra_payments_agreement !== undefined) this.requiresExtraPaymentsAgreement = shopData.requires_extra_payments_agreement;
    if (shopData.password_enabled !== undefined) this.passwordEnabled = shopData.password_enabled;
    if (shopData.has_storefront !== undefined) this.hasStorefront = shopData.has_storefront;
    if (shopData.primary_location_id !== undefined) this.primaryLocationID = shopData.primary_location_id;
    if (shopData.checkout_api_supported !== undefined) this.checkoutAPISupported = shopData.checkout_api_supported;
    if (shopData.multi_location_enabled !== undefined) this.multiLocationEnabled = shopData.multi_location_enabled;
    if (shopData.setup_required !== undefined) this.setupRequired = shopData.setup_required;
    if (shopData.pre_launch_enabled !== undefined) this.preLaunchEnabled = shopData.pre_launch_enabled;
    if (Array.isArray(shopData.enabled_presentment_currencies)) this.enabledPresentmentCurrencies = shopData.enabled_presentment_currencies;
    if (isValid(shopData.created_at)) this.created = shopData.created_at;
    if (isValid(shopData.updated_at)) this.updated = shopData.updated_at;
    if (isValid(shopData.created_at) && !isValid(this.createdAt)) this.createdAt = shopData.created_at;
    if (isValid(shopData.updated_at) && !isValid(this.updatedAt)) this.updatedAt = shopData.updated_at;
    if (!isValid(this.source)) this.source = String(this.dataSource || DataSources.firebase);

    let ID = genID(this.type, this.number, this.name || `Shop`);
    let { id, title, uuid } = ID;
    if (!isValid(this.id)) this.id = id;
    if (!isValid(this.uuid)) this.uuid = uuid;
    if (!isValid(this.title)) this.title = title;
    if (!isValid(this.properties)) this.properties = countPropertiesInObject(this) + 1;
  }
}
